# Generated by Django 4.0.6 on 2022-11-27 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('DONE', 'DONE')], max_length=10)),
            ],
        ),
    ]
