# Generated by Django 4.0.6 on 2022-12-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('DONE', 'DONE')], default='TODO', max_length=10),
        ),
    ]
